title: 中山功太 (Kouta Nakayama)
remote_theme: pages-themes/slate@v0.2.0
encding: utf-8
plugins: 
  - jekyll-github-metadata
  - jekyll-avatar
  - jekyll-remote-theme
  - jekyll-sitemap
github : [metadata]
repository: k141303/k141303.github.io