source 'https://rubygems.org'
gem 'jekyll', '~> 3.9'
gem 'github-pages', group: :jekyll_plugins
gem 'bundler', '~> 2.3'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-github-metadata'
gem 'jekyll-remote-theme'
gem 'webrick', '~> 1.8'
gem 'jekyll-avatar', '~> 0.8.0'
gem 'jekyll-theme-clean-blog'
gem 'jekyll-seo-tag'